import { createApp } from 'vue';
import { createPinia } from 'pinia';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import VXETable from 'vxe-table';
import 'vxe-table/lib/style.css';
import BasicComponents from 'srit-basic-components';
import App from './App.vue';
import router from './router';
import './styles/index.css';
import './mock';
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.use(ElementPlus);
app.use(VXETable);
app.use(BasicComponents);
app.mount('#app');
